// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TalentMachine.Api.Data;

#nullable disable

namespace TalentMachine.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723011611_RehearsalRoom")]
    partial class RehearsalRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TalentMachine.Api.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CastGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("CastGroups");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CastMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CastGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CastGroupId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "PerformerId")
                        .IsUnique();

                    b.ToTable("CastMemberships");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Conflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weekday")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "PerformerId");

                    b.ToTable("Conflicts");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CostumeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("MusicalNumberId", "PerformerId")
                        .IsUnique();

                    b.ToTable("CostumeAssignments");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CostumePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessories")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Shoes")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MusicalNumberId");

                    b.HasIndex("TenantId");

                    b.ToTable("CostumePieces");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FormationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusicalNumberId");

                    b.HasIndex("TenantId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Guardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcceptedByClerkUserId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.MusicalNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChoreographerStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("CostumeLabel")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SceneId")
                        .HasColumnType("integer");

                    b.Property<string>("TeachStatus")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("ChoreographerStaffId");

                    b.HasIndex("SceneId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "OrderIndex");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.NumberCast", b =>
                {
                    b.Property<int>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("MusicalNumberId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.ToTable("NumberCasts");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.NumberCharacter", b =>
                {
                    b.Property<int>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("MusicalNumberId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("NumberCharacters");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.PerformerGuardian", b =>
                {
                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("GuardianId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("PerformerId", "GuardianId");

                    b.HasIndex("GuardianId");

                    b.HasIndex("TenantId");

                    b.ToTable("PerformerGuardians");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("OpeningDate")
                        .HasColumnType("date");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TenantId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.ProductionAccess", b =>
                {
                    b.Property<int>("MembershipId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("MembershipId", "ProductionId");

                    b.HasIndex("ProductionId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProductionAccesses");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.ProductionStaff", b =>
                {
                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("ProductionId", "StaffMemberId", "Role");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProductionStaff");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Prop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "OrderIndex");

                    b.ToTable("Props");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.PropAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Handler")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PresetLocation")
                        .HasColumnType("text");

                    b.Property<int>("PropId")
                        .HasColumnType("integer");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<string>("StrikeTo")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropId");

                    b.HasIndex("SceneId");

                    b.HasIndex("TenantId");

                    b.ToTable("PropAssignments");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Rehearsal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("MusicalNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MusicalNumberId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "Date");

                    b.ToTable("Rehearsals");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.RehearsalAttendance", b =>
                {
                    b.Property<int>("RehearsalId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("RehearsalId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.ToTable("RehearsalAttendances");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.RehearsalAttendee", b =>
                {
                    b.Property<int>("RehearsalId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("RehearsalId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.ToTable("RehearsalAttendees");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProductionId", "OrderIndex");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.SceneCharacter", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("SceneCharacters");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Year");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CastMembership", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.CastGroup", "CastGroup")
                        .WithMany()
                        .HasForeignKey("CastGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastGroup");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Conflict", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CostumeAssignment", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.CostumePiece", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Formation", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Membership", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.MusicalNumber", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Act", "Act")
                        .WithMany()
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TalentMachine.Api.Models.StaffMember", "Choreographer")
                        .WithMany()
                        .HasForeignKey("ChoreographerStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TalentMachine.Api.Models.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Act");

                    b.Navigation("Choreographer");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.NumberCast", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.NumberCharacter", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.PerformerGuardian", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Guardian", "Guardian")
                        .WithMany()
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Production", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.ProductionAccess", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.ProductionStaff", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.StaffMember", "StaffMember")
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("StaffMember");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.PropAssignment", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Prop", "Prop")
                        .WithMany()
                        .HasForeignKey("PropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prop");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Rehearsal", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.MusicalNumber", "MusicalNumber")
                        .WithMany()
                        .HasForeignKey("MusicalNumberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TalentMachine.Api.Models.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalNumber");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.RehearsalAttendance", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Rehearsal", "Rehearsal")
                        .WithMany()
                        .HasForeignKey("RehearsalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Rehearsal");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.RehearsalAttendee", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Rehearsal", "Rehearsal")
                        .WithMany()
                        .HasForeignKey("RehearsalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Rehearsal");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Role", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Scene", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Act", "Act")
                        .WithMany()
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Act");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.SceneCharacter", b =>
                {
                    b.HasOne("TalentMachine.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMachine.Api.Models.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("TalentMachine.Api.Models.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
